### ISSUE TITLE
Password edit field

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MetroPass#22]
See correct value/have passwordfield
Confirmation password does validation

**Comment by kevinkuebler** [comment]
This is basically working now, except I can't get it to use a PasswordBox instead of a TextBox. If you change it to PasswordBox and set the IsPasswordRevealButtonEnabled to true, it displays as a password box, but it never displays the reveal button. I don't know why, because the PasswordBox on the load screen works fine.

**Comment by kevinkuebler** [comment]
Decided to not make these PasswordBoxes since the behavior on WinRT is kind of annoying. If focus comes back to a PasswordBox that already has text in it, the reveal button doesn't appear unless you clear the contents and start typing again. This is not very user friendly when you just want to view the edit screen to see what a password is.

We'll leave this as is for now unless we hear from users that they want a different behavior.

**Comment by kevinkuebler** [comment]
Added a hack to provide the Password and Confirm fields with immediate (as-you-type) validation. Hack was needed due to lack of UpdateSourceTrigger property in WinRT XAML.
